[package]
name = "rocks"
version = "0.1.0"
edition = "2021"
default-run = "rocks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]
bench = false

[dependencies]
